name: "Release Artifact"
on:
  release:
    types:
      - published

env:
  GODOT_VERSION: 3.6

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: docker.io/smks/godot-ci:3.6
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up export templates
        run: |
          mkdir -v -p ~/.local/share/godot/templates/
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable

      - name: Export with Godot
        run: |
          mkdir --verbose --parents ./export/linux
          godot --no-window --path=./project.godot --export "Linux/X11" ./export/linux/ROTA.x86_64

  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Upload run artifact
        uses: actions/upload-artifact@v4
        with:
          name: rota-linux
          path: |
            export/linux/ROTA.x86_64
            export/linux/ROTA.pck

      - name: Upload release artifact
        uses:
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload
          '${{ github.ref_name }}' export/linux/ROTA*
          --repo '${{ github.repository }}'